export default
    [
        {
            'name':'Basic基础组件',
            "info":[   
                    {
                        'name':'Button',
                        'url':'url'
                    },  
                    {
                        'name':'Loading',
                        'url':'url'
                    },  
                    {
                        'name':'Tip',
                        'url':'url'
                    },  
                    {           
                        'name':'ToolBar',
                        'url':'url'
                    },   
                ],
        },
        {
            'name':'Form基础组件',
            "info":[   
                    {
                        'name':'Checkbox',
                        'url':'url'                   
                    },  
                    {
                        'name':'CheckboxGroup',
                        'url':'url'   
                    },  
                    {
                        'name':'Checker',
                        'url':'url'   
                    },  
                    {
                        'name':'Radio',
                        'url':'url'  
                    }, 
                    {
                        'name':'Input',
                        'url':'url'  
                    }, 
                    {
                        'name':'Textarea',
                        'url':'url'  
                    }, 
                    {
                        'name':'Select',
                        'url':'url' 
                    }, 
                    {
                        'name':'Switch',
                        'url':'url'                     
                    }, 
                    {
                        'name':'Rate',
                        'url':'url'   
                    }, 
                    {
                        'name':'Validator',
                        'url':'url'   
                    },
                    {
                        'name':'Upload',
                        'url':'url' 
                    }, 
                    {
                        'name':'Form',
                        'url':'url' 
                    },    
                ],
        },
        {
            'name':'Popup弹窗组件',
            "info":[   
                    {
                        'name':'Popup',
                        'url':'url' 
                    },  
                    {
                        'name':'Toast',
                        'url':'url' 
                    },  
                    {
                        'name':'CascadePicker',
                        'url':'url'
                    },  
                    {
                        'name':'DatePicker',
                        'url':'url'
                    },
                    {
                        'name':'TimePicker',
                        'url':'url'
                    },   
                    {
                        'name':'Dialog',
                        'url':'url'
                    },   
                    {
                        'name':'ActionSheet',
                        'url':'url'
                    },   
                    {
                        'name':'Drawer',
                        'url':'url'
                    },   
                    {
                        'name':'ImagePreview',
                        'url':'url'
                    },   
                    
                ],
        },
        {
            'name':'Scroll滚动组件',
            "info":[   
                    {
                        'name':'Scroll',
                        'url':'url'
                    },  
                    {
                        'name':'Slide',
                        'url':'url'
                    },  
                    {
                        'name':'IndexList',
                        'url':'url'
                    },  
                    {
                        'name':'Swipe',
                        'url':'url'
                    },  
                    {
                        'name':'Sticky',
                        'url':'url'
                    },  
                    {
                        'name':'ScrollNavBar',
                        'url':'url'
                    },  
                    {
                        'name':'ScrollNav',
                        'url':'url'
                    },  
                    {
                        'name':'RecycleList',
                        'url':'url'
                    },   
                ],
        }
    ]
